const data1=(req,res)=>{
    res.send([
      {
        id:1,
        img:"https://pngimg.com/uploads/jeans/small/jeans_PNG5776.png",
      },
      {
        id:2,
        img:"https://media.istockphoto.com/id/482948743/photo/blank-white-t-shirt-front-with-clipping-path.jpg?b=1&s=170667a&w=0&k=20&c=0ZVjmNfhpgTmkvGZk2Um2UnZEdTT14rcUsQeTBmhuWA=",
      },
      {
        id:3,
        img:"https://media.istockphoto.com/id/483960103/photo/blank-black-t-shirt-front-with-clipping-path.jpg?b=1&s=170667a&w=0&k=20&c=BcPtyKJxhRevZV29PDZ1y-le2WbmH6Xf4O_lkmopDxg=",
      },
      {
        id:4,
        img:"https://pngimg.com/uploads/jeans/small/jeans_PNG5773.png",
      },
      {
        id:5,
        img:"https://www.pngall.com/wp-content/uploads/5/Shirt-PNG-File.png",
      },
      {
        id:6,
        img:"https://pngimg.com/uploads/jeans/small/jeans_PNG5747.png",
      },
      {
        id:7,
        img:"https://purepng.com/public/uploads/large/purepng.com-brown-hathatsstandard-sizenicewooden-1421526360375drgao.png",
      },
      {
        id:8,
        img:"https://www.pngall.com/wp-content/uploads/5/Long-Sleeve-Shirt-PNG-Image.png",
      },
        ]);
      }
module.exports.apicontroller1=data1;


